all parameter  {'node_num': 100, 'seed': 259, 'dim': 2, 'hid': 64, 'epoch_num': 700, 'batch_size': 1024, 'lr_net': 0.004, 'lr_dyn': 0.001, 'lr_state': 0.1, 'miss_percent': 0.1, 'data_path': '/data/chenmy/voter/seed1051email14315000', 'temp': 1, 'drop_frac': 1, 'cuda': 3}
tensor([0., 1., 0., 1., 1., 1., 1., 0., 1., 0.], device='cuda:3')
start_time: 2020-10-27 13:02:24
data_num 10533 object_matrix tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:3')
Traceback (most recent call last):
  File "voter_nc_karate.py", line 233, in <module>
    loss_y,mse_y = train_dyn_net_state()
  File "voter_nc_karate.py", line 149, in train_dyn_net_state
    adj_col[:-del_num] = observed_adj[j].cuda()
RuntimeError: The expanded size of the tensor (90) must match the existing size (133) at non-singleton dimension 0.  Target sizes: [90].  Tensor sizes: [133]
